"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 05:59:19.368453
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=7), nullable=False),
    sa.Column('is_other', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind in ('income','expense')", name='ck_categories_kind'),
    sa.CheckConstraint("status in ('active','archived')", name='ck_categories_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_categories_kind_name', 'categories', ['kind', sa.literal_column('lower(name)')], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','archived')", name='ck_teams_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_teams_name', 'teams', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=80), nullable=False),
    sa.Column('mob_no', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','archived')", name='ck_players_status'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_index('uq_players_team_name', 'players', ['team_id', sa.literal_column('lower(player_name)')], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('item_description', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('surplus_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=60), nullable=True),
    sa.Column('void_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','voided','reversed')", name='ck_transactions_status'),
    sa.CheckConstraint("type in ('income','expense','transfer')", name='ck_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_team_date', 'transactions', ['team_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_team_id'), 'transactions', ['team_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=6), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("(kind = 'team' and player_id is null) or (kind = 'player' and player_id is not null)", name='ck_accounts_shape'),
    sa.CheckConstraint("kind in ('team','player')", name='ck_accounts_kind'),
    sa.CheckConstraint("status in ('active','archived')", name='ck_accounts_status'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_accounts_team_id'), 'accounts', ['team_id'], unique=False)
    op.create_index('uq_one_team_account', 'accounts', ['team_id'], unique=True, postgresql_where=sa.text("kind = 'team'"), sqlite_where=sa.text("kind = 'team'"))
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('settlement_status', sa.Integer(), nullable=False),
    sa.Column('settled_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocated_amount > 0', name='ck_allocations_amount'),
    sa.CheckConstraint('settlement_status in (0, 1)', name='ck_allocations_settlement'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['settled_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_account_id'), 'allocations', ['account_id'], unique=False)
    op.create_index(op.f('ix_allocations_transaction_id'), 'allocations', ['transaction_id'], unique=False)
    op.create_index('uq_allocation_party', 'allocations', ['transaction_id', 'account_id'], unique=True)
    op.create_table('opening_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('transaction_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.CheckConstraint("role in ('paid_by','account_in','account_out')", name='ck_txn_accounts_role'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_accounts_account_id'), 'transaction_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_accounts_transaction_id'), 'transaction_accounts', ['transaction_id'], unique=False)
    op.create_index('uq_txn_account_role', 'transaction_accounts', ['transaction_id', 'account_id', 'role'], unique=True)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=13), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('settlement_transaction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind in ('reimbursement','collection')", name='ck_settlements_kind'),
    sa.CheckConstraint("status in ('active','reversed')", name='ck_settlements_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_transaction_id')
    )
    op.create_index(op.f('ix_settlements_transaction_id'), 'settlements', ['transaction_id'], unique=False)
    op.create_index('uq_active_settlement', 'settlements', ['transaction_id', 'account_id', 'kind'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###

    # audit_log is append-only: block UPDATE and DELETE at the database level.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("""
            CREATE FUNCTION audit_log_immutable() RETURNS trigger AS $$
            BEGIN RAISE EXCEPTION 'audit_log is append-only'; END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE TRIGGER audit_log_no_change BEFORE UPDATE OR DELETE ON audit_log
            FOR EACH ROW EXECUTE FUNCTION audit_log_immutable()
        """)
    elif bind.dialect.name == "sqlite":
        for verb in ("UPDATE", "DELETE"):
            op.execute(f"""
                CREATE TRIGGER audit_log_no_{verb.lower()} BEFORE {verb} ON audit_log
                BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END
            """)



def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_change ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS audit_log_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_settlement', table_name='settlements', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_settlements_transaction_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('uq_txn_account_role', table_name='transaction_accounts')
    op.drop_index(op.f('ix_transaction_accounts_transaction_id'), table_name='transaction_accounts')
    op.drop_index(op.f('ix_transaction_accounts_account_id'), table_name='transaction_accounts')
    op.drop_table('transaction_accounts')
    op.drop_table('opening_balances')
    op.drop_index('uq_allocation_party', table_name='allocations')
    op.drop_index(op.f('ix_allocations_transaction_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_account_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index('uq_one_team_account', table_name='accounts', postgresql_where=sa.text("kind = 'team'"), sqlite_where=sa.text("kind = 'team'"))
    op.drop_index(op.f('ix_accounts_team_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_transactions_team_id'), table_name='transactions')
    op.drop_index('ix_transactions_team_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('uq_players_team_name', table_name='players')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index('uq_teams_name', table_name='teams')
    op.drop_table('teams')
    op.drop_index('uq_categories_kind_name', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
