"""add created_at to players and adhoc_income

Revision ID: f79a56a0b852
Revises: 56d22a271f0a
Create Date: 2026-09-06 17:12:04.104885

"""
from alembic import op
import sqlalchemy as sa


revision = 'f79a56a0b852'
down_revision = '56d22a271f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adhoc_income', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'created_at')
    op.drop_column('adhoc_income', 'created_at')
    # ### end Alembic commands ###
